.TH PENTER 1 "630 MTG"
.SH NAME
penter \- Program the key definition for the enter key. 
.SH SYNOPSIS
.B penter -n | "string"
.SH DESCRIPTION
The 
.I penter
program will set the key definition for the
<enter> key to "string" for the window 
.I penter
is invoked in.
Each window can have a different definition
for the enter key, with a maximum of 4 characters>
The \fB-n\fR option will set the <enter> key to a "\n" (a return).
