.TH XTS 1 layers
.SH NAME
\f4xts\f1 \- print xt protocol statistics
.SH SYNOPSIS
\f4xts\f1
.SH DESCRIPTION
The
\f4xts\fP
command
is a debugging tool for \f4layers\fP(1).
It displays accumulated statistics
for all channels.
The statistics are
printed one item per line on the standard output.
.SH SEE ALSO
\f4layers\fP(1), \f4xtagent\f1(1), \f4xtt\fP(1), \f4xtproto\fP(5).
